name: Deploy to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set API key environment variable
              env:
                  TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
              run: |
                  echo "window.TMDB_API_KEY = '$TMDB_API_KEY';" > secrets.js

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./
